// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reinforced.Samples.ToyFactory.Data;

namespace Reinforced.Samples.ToyFactory.Data.Migrations
{
    [DbContext(typeof(ToyFactoryDbContext))]
    [Migration("20210216084523_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("Reinforced.Samples.ToyFactory.Logic.Entities.Blueprint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToyTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ToyTypeId");

                    b.ToTable("Blueprints");
                });

            modelBuilder.Entity("Reinforced.Samples.ToyFactory.Logic.Entities.BlueprintResources", b =>
                {
                    b.Property<int>("BlueprintId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResourceId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.HasKey("BlueprintId", "ResourceId");

                    b.HasIndex("ResourceId");

                    b.ToTable("BlueprintResources");
                });

            modelBuilder.Entity("Reinforced.Samples.ToyFactory.Logic.Entities.ToyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ToyTypes");
                });

            modelBuilder.Entity("Reinforced.Samples.ToyFactory.Logic.Warehouse.Entities.MeasurementUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MeasurementUnits");
                });

            modelBuilder.Entity("Reinforced.Samples.ToyFactory.Logic.Warehouse.Entities.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeasurementUnitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("StockQuantity")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementUnitId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("Reinforced.Samples.ToyFactory.Logic.Warehouse.Entities.Suppliement.ResourceSupply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemsCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ResourceSupplies");
                });

            modelBuilder.Entity("Reinforced.Samples.ToyFactory.Logic.Warehouse.Entities.Suppliement.ResourceSupplyItem", b =>
                {
                    b.Property<int>("ResourceSupplyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResourceId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.HasKey("ResourceSupplyId", "ResourceId");

                    b.HasIndex("ResourceId");

                    b.ToTable("ResourceSupplyItems");
                });

            modelBuilder.Entity("Reinforced.Samples.ToyFactory.Logic.Warehouse.Entities.Suppliement.ResourceSupplyStatusHistoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Next")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Previous")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResourceSupplyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ResourceSupplyId");

                    b.ToTable("ResourceSupplyStatusHistoryItems");
                });

            modelBuilder.Entity("Reinforced.Samples.ToyFactory.Logic.Entities.Blueprint", b =>
                {
                    b.HasOne("Reinforced.Samples.ToyFactory.Logic.Entities.ToyType", "ToyType")
                        .WithMany()
                        .HasForeignKey("ToyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToyType");
                });

            modelBuilder.Entity("Reinforced.Samples.ToyFactory.Logic.Entities.BlueprintResources", b =>
                {
                    b.HasOne("Reinforced.Samples.ToyFactory.Logic.Entities.Blueprint", "Blueprint")
                        .WithMany()
                        .HasForeignKey("BlueprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reinforced.Samples.ToyFactory.Logic.Warehouse.Entities.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blueprint");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Reinforced.Samples.ToyFactory.Logic.Warehouse.Entities.Resource", b =>
                {
                    b.HasOne("Reinforced.Samples.ToyFactory.Logic.Warehouse.Entities.MeasurementUnit", "MeasurementUnit")
                        .WithMany()
                        .HasForeignKey("MeasurementUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeasurementUnit");
                });

            modelBuilder.Entity("Reinforced.Samples.ToyFactory.Logic.Warehouse.Entities.Suppliement.ResourceSupplyItem", b =>
                {
                    b.HasOne("Reinforced.Samples.ToyFactory.Logic.Warehouse.Entities.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reinforced.Samples.ToyFactory.Logic.Warehouse.Entities.Suppliement.ResourceSupply", "ResourceSupply")
                        .WithMany()
                        .HasForeignKey("ResourceSupplyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("ResourceSupply");
                });

            modelBuilder.Entity("Reinforced.Samples.ToyFactory.Logic.Warehouse.Entities.Suppliement.ResourceSupplyStatusHistoryItem", b =>
                {
                    b.HasOne("Reinforced.Samples.ToyFactory.Logic.Warehouse.Entities.Suppliement.ResourceSupply", "ResourceSupply")
                        .WithMany()
                        .HasForeignKey("ResourceSupplyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResourceSupply");
                });
#pragma warning restore 612, 618
        }
    }
}
